name: 🔄 Auto‑update Summer Movie Pool Leaderboard

on:
  schedule:
    # every day at 12:00 UTC
    - cron:  '0 12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Generate leaderboard
      run: |
        mkdir -p docs
        # this will produce leaderboard.csv and leaderboard.html
        python summer_pool.py \
          --entries entries.csv \
          --csv summer_movies.csv \
          --debug

        # move them into docs for Pages
        mv leaderboard.html docs/index.html
        mv leaderboard.csv docs/leaderboard.csv

    - name: Commit & push changes
      run: |
        git config user.name  "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/index.html docs/leaderboard.csv
        git diff --quiet || git commit -m "🔄 Auto‑update leaderboard"
        git push
