name: 🔄 Auto‑update Summer Movie Pool Leaderboard

# trigger on daily schedule, manual dispatch, or any push to main
on:
  schedule:
    - cron:  '0 12 * * *'   # every day at 12:00 UTC
  workflow_dispatch: {}
  push:
    branches:
      - main

# allow the action to push back to the repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Generate leaderboard
      run: |
        # ensure docs/ exists
        mkdir -p docs

        # run your script, pointing output to docs/index.html
        # adjust flags if your script signature changed
        python summer_pool.py \
          --entries entries.csv \
          --csv summer_movies.csv \
          --output docs/index.html

        # move the CSV too
        mv leaderboard.csv docs/leaderboard.csv

    - name: Commit & push changes
      run: |
        git config user.name  "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/index.html docs/leaderboard.csv
        git diff --quiet || git commit -m "🔄 Auto‑update leaderboard"
        git push
